### ISSUE TITLE
TRADE Rockies-Dodgers 3/29/18

### ISSUE THREAD

**Issue by sasakisan12** [kpainton/OOTP-Online-League#10]
Rockies
3B Tyler Nevin
LF Ian Desmond 10%
C Austin Bernard
$1700000

Dodgers
CL Tony Gonsolin
C Will D Smith
RP WIlmer Font 100%
![screen shot 2018-05-26 at 1 31 36 am](https://user-images.githubusercontent.com/39469341/40574335-e79196ee-6084-11e8-8d39-4e7287965ec8.png)

**Comment by kpainton** [comment]
DOES NOT WORK

**Comment by rkumar921** [comment]
BOO MATT U R A BAD GM

**Comment by rkumar921** [comment]
MATT STOP BEING A BAD GM

**Comment by rkumar921** [comment]
MATT U R STILL A BAD GM
